Get all aircrafts
shaz-ahammed/airport-app-backend pull request #37
Opened 2024-04-25 07:40 UTC by shaz-ahammed

2024-04-26 17:22 UTC, vraravam requested changes
Lets wait for other PR #41  to be merged, before this is picked up

2024-04-30 04:31 UTC, vraravam approved these changes

2024-04-30 04:36 UTC, jai-charan commented on controllers/aircraft_controller.go
> +func (acr *AircraftController) HandleGetAllAircrafts(ctx *gin.Context) {
Rename the reciever name instead of acr

2024-04-30 04:51 UTC, jai-charan approved these changes

2024-04-30 04:51 UTC, SathyaRupa approved these changes

2024-04-30 04:52 UTC, merged