#19 [Jayashakthi|Sathya] Update airline Details
shaz-ahammed/airport-app-backend pull request #38
Opened 2024-04-25 09:31 UTC by Jayashakthi28

- Created PUT endpoint
- Implemented Swagger
- Created test for the controller

2024-04-26 07:23 UTC, shaz-ahammed approved these changes
Use the builder pattern  to create airline model's instance after the builder factory pattern's PR has been merged

2024-04-26 17:21 UTC, vraravam requested changes
Lets wait for other PR to be merged, before this is picked up

2024-04-30 09:09 UTC, SathyaRupa commented
Made the changes

2024-04-30 09:37 UTC, vraravam approved these changes

2024-04-30 09:43 UTC, shaz-ahammed approved these changes

2024-04-30 09:44 UTC, merged